[package]
name = "stunning-tribble"
version = "0.1.1"
edition = "2024"
repository = "https://github.com/yehezkieldio/stunning-tribble"

[[bin]]
name = "stunning-tribble"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"

[profile.dist]
inherits = "release"
lto = "thin"
