[workspace]
members = ["cargo:."]

[dist]
dist = true
cargo-dist-version = "0.30.3"
ci = "github"
installers = ["npm"]
publish-jobs = ["npm"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
allow-dirty = ["ci"]
pr-run-mode = "upload"
